/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResetPasswordTokenRouteImport } from './routes/reset-password.$token'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedMonetizationTransactionsIndexRouteImport } from './routes/_authenticated/monetization/transactions/index'
import { Route as AuthenticatedMonetizationTaxesIndexRouteImport } from './routes/_authenticated/monetization/taxes/index'
import { Route as AuthenticatedMonetizationPlansIndexRouteImport } from './routes/_authenticated/monetization/plans/index'
import { Route as AuthenticatedMonetizationPaymentMethodsIndexRouteImport } from './routes/_authenticated/monetization/payment-methods/index'
import { Route as AuthenticatedMonetizationCouponsIndexRouteImport } from './routes/_authenticated/monetization/coupons/index'
import { Route as AuthenticatedEngagementReviewsIndexRouteImport } from './routes/_authenticated/engagement/reviews/index'
import { Route as AuthenticatedEngagementReportsIndexRouteImport } from './routes/_authenticated/engagement/reports/index'
import { Route as AuthenticatedEngagementCommentsIndexRouteImport } from './routes/_authenticated/engagement/comments/index'
import { Route as AuthenticatedContentVideosIndexRouteImport } from './routes/_authenticated/content/videos/index'
import { Route as AuthenticatedContentTvShowsIndexRouteImport } from './routes/_authenticated/content/tv-shows/index'
import { Route as AuthenticatedContentSeasonsIndexRouteImport } from './routes/_authenticated/content/seasons/index'
import { Route as AuthenticatedContentMoviesIndexRouteImport } from './routes/_authenticated/content/movies/index'
import { Route as AuthenticatedContentGenresIndexRouteImport } from './routes/_authenticated/content/genres/index'
import { Route as AuthenticatedContentEpisodesIndexRouteImport } from './routes/_authenticated/content/episodes/index'
import { Route as AuthenticatedContentChannelsIndexRouteImport } from './routes/_authenticated/content/channels/index'
import { Route as AuthenticatedContentCastCrewIndexRouteImport } from './routes/_authenticated/content/cast-crew/index'
import { Route as AuthenticatedCmsSettingsIndexRouteImport } from './routes/_authenticated/cms/settings/index'
import { Route as AuthenticatedCmsPagesIndexRouteImport } from './routes/_authenticated/cms/pages/index'
import { Route as AuthenticatedCmsBannersIndexRouteImport } from './routes/_authenticated/cms/banners/index'
import { Route as AuthenticatedContentTvShowsIdRouteImport } from './routes/_authenticated/content/tv-shows/$id'
import { Route as AuthenticatedContentSeasonsIdRouteImport } from './routes/_authenticated/content/seasons/$id'
import { Route as AuthenticatedContentMoviesIdRouteImport } from './routes/_authenticated/content/movies/$id'
import { Route as AuthenticatedContentEpisodesIdRouteImport } from './routes/_authenticated/content/episodes/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMonetizationTransactionsIndexRoute =
  AuthenticatedMonetizationTransactionsIndexRouteImport.update({
    id: '/monetization/transactions/',
    path: '/monetization/transactions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMonetizationTaxesIndexRoute =
  AuthenticatedMonetizationTaxesIndexRouteImport.update({
    id: '/monetization/taxes/',
    path: '/monetization/taxes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMonetizationPlansIndexRoute =
  AuthenticatedMonetizationPlansIndexRouteImport.update({
    id: '/monetization/plans/',
    path: '/monetization/plans/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMonetizationPaymentMethodsIndexRoute =
  AuthenticatedMonetizationPaymentMethodsIndexRouteImport.update({
    id: '/monetization/payment-methods/',
    path: '/monetization/payment-methods/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMonetizationCouponsIndexRoute =
  AuthenticatedMonetizationCouponsIndexRouteImport.update({
    id: '/monetization/coupons/',
    path: '/monetization/coupons/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEngagementReviewsIndexRoute =
  AuthenticatedEngagementReviewsIndexRouteImport.update({
    id: '/engagement/reviews/',
    path: '/engagement/reviews/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEngagementReportsIndexRoute =
  AuthenticatedEngagementReportsIndexRouteImport.update({
    id: '/engagement/reports/',
    path: '/engagement/reports/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEngagementCommentsIndexRoute =
  AuthenticatedEngagementCommentsIndexRouteImport.update({
    id: '/engagement/comments/',
    path: '/engagement/comments/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContentVideosIndexRoute =
  AuthenticatedContentVideosIndexRouteImport.update({
    id: '/content/videos/',
    path: '/content/videos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContentTvShowsIndexRoute =
  AuthenticatedContentTvShowsIndexRouteImport.update({
    id: '/content/tv-shows/',
    path: '/content/tv-shows/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContentSeasonsIndexRoute =
  AuthenticatedContentSeasonsIndexRouteImport.update({
    id: '/content/seasons/',
    path: '/content/seasons/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContentMoviesIndexRoute =
  AuthenticatedContentMoviesIndexRouteImport.update({
    id: '/content/movies/',
    path: '/content/movies/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContentGenresIndexRoute =
  AuthenticatedContentGenresIndexRouteImport.update({
    id: '/content/genres/',
    path: '/content/genres/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContentEpisodesIndexRoute =
  AuthenticatedContentEpisodesIndexRouteImport.update({
    id: '/content/episodes/',
    path: '/content/episodes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContentChannelsIndexRoute =
  AuthenticatedContentChannelsIndexRouteImport.update({
    id: '/content/channels/',
    path: '/content/channels/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContentCastCrewIndexRoute =
  AuthenticatedContentCastCrewIndexRouteImport.update({
    id: '/content/cast-crew/',
    path: '/content/cast-crew/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCmsSettingsIndexRoute =
  AuthenticatedCmsSettingsIndexRouteImport.update({
    id: '/cms/settings/',
    path: '/cms/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCmsPagesIndexRoute =
  AuthenticatedCmsPagesIndexRouteImport.update({
    id: '/cms/pages/',
    path: '/cms/pages/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCmsBannersIndexRoute =
  AuthenticatedCmsBannersIndexRouteImport.update({
    id: '/cms/banners/',
    path: '/cms/banners/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContentTvShowsIdRoute =
  AuthenticatedContentTvShowsIdRouteImport.update({
    id: '/content/tv-shows/$id',
    path: '/content/tv-shows/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContentSeasonsIdRoute =
  AuthenticatedContentSeasonsIdRouteImport.update({
    id: '/content/seasons/$id',
    path: '/content/seasons/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContentMoviesIdRoute =
  AuthenticatedContentMoviesIdRouteImport.update({
    id: '/content/movies/$id',
    path: '/content/movies/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContentEpisodesIdRoute =
  AuthenticatedContentEpisodesIdRouteImport.update({
    id: '/content/episodes/$id',
    path: '/content/episodes/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/content/episodes/$id': typeof AuthenticatedContentEpisodesIdRoute
  '/content/movies/$id': typeof AuthenticatedContentMoviesIdRoute
  '/content/seasons/$id': typeof AuthenticatedContentSeasonsIdRoute
  '/content/tv-shows/$id': typeof AuthenticatedContentTvShowsIdRoute
  '/cms/banners': typeof AuthenticatedCmsBannersIndexRoute
  '/cms/pages': typeof AuthenticatedCmsPagesIndexRoute
  '/cms/settings': typeof AuthenticatedCmsSettingsIndexRoute
  '/content/cast-crew': typeof AuthenticatedContentCastCrewIndexRoute
  '/content/channels': typeof AuthenticatedContentChannelsIndexRoute
  '/content/episodes': typeof AuthenticatedContentEpisodesIndexRoute
  '/content/genres': typeof AuthenticatedContentGenresIndexRoute
  '/content/movies': typeof AuthenticatedContentMoviesIndexRoute
  '/content/seasons': typeof AuthenticatedContentSeasonsIndexRoute
  '/content/tv-shows': typeof AuthenticatedContentTvShowsIndexRoute
  '/content/videos': typeof AuthenticatedContentVideosIndexRoute
  '/engagement/comments': typeof AuthenticatedEngagementCommentsIndexRoute
  '/engagement/reports': typeof AuthenticatedEngagementReportsIndexRoute
  '/engagement/reviews': typeof AuthenticatedEngagementReviewsIndexRoute
  '/monetization/coupons': typeof AuthenticatedMonetizationCouponsIndexRoute
  '/monetization/payment-methods': typeof AuthenticatedMonetizationPaymentMethodsIndexRoute
  '/monetization/plans': typeof AuthenticatedMonetizationPlansIndexRoute
  '/monetization/taxes': typeof AuthenticatedMonetizationTaxesIndexRoute
  '/monetization/transactions': typeof AuthenticatedMonetizationTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/content/episodes/$id': typeof AuthenticatedContentEpisodesIdRoute
  '/content/movies/$id': typeof AuthenticatedContentMoviesIdRoute
  '/content/seasons/$id': typeof AuthenticatedContentSeasonsIdRoute
  '/content/tv-shows/$id': typeof AuthenticatedContentTvShowsIdRoute
  '/cms/banners': typeof AuthenticatedCmsBannersIndexRoute
  '/cms/pages': typeof AuthenticatedCmsPagesIndexRoute
  '/cms/settings': typeof AuthenticatedCmsSettingsIndexRoute
  '/content/cast-crew': typeof AuthenticatedContentCastCrewIndexRoute
  '/content/channels': typeof AuthenticatedContentChannelsIndexRoute
  '/content/episodes': typeof AuthenticatedContentEpisodesIndexRoute
  '/content/genres': typeof AuthenticatedContentGenresIndexRoute
  '/content/movies': typeof AuthenticatedContentMoviesIndexRoute
  '/content/seasons': typeof AuthenticatedContentSeasonsIndexRoute
  '/content/tv-shows': typeof AuthenticatedContentTvShowsIndexRoute
  '/content/videos': typeof AuthenticatedContentVideosIndexRoute
  '/engagement/comments': typeof AuthenticatedEngagementCommentsIndexRoute
  '/engagement/reports': typeof AuthenticatedEngagementReportsIndexRoute
  '/engagement/reviews': typeof AuthenticatedEngagementReviewsIndexRoute
  '/monetization/coupons': typeof AuthenticatedMonetizationCouponsIndexRoute
  '/monetization/payment-methods': typeof AuthenticatedMonetizationPaymentMethodsIndexRoute
  '/monetization/plans': typeof AuthenticatedMonetizationPlansIndexRoute
  '/monetization/taxes': typeof AuthenticatedMonetizationTaxesIndexRoute
  '/monetization/transactions': typeof AuthenticatedMonetizationTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/content/episodes/$id': typeof AuthenticatedContentEpisodesIdRoute
  '/_authenticated/content/movies/$id': typeof AuthenticatedContentMoviesIdRoute
  '/_authenticated/content/seasons/$id': typeof AuthenticatedContentSeasonsIdRoute
  '/_authenticated/content/tv-shows/$id': typeof AuthenticatedContentTvShowsIdRoute
  '/_authenticated/cms/banners/': typeof AuthenticatedCmsBannersIndexRoute
  '/_authenticated/cms/pages/': typeof AuthenticatedCmsPagesIndexRoute
  '/_authenticated/cms/settings/': typeof AuthenticatedCmsSettingsIndexRoute
  '/_authenticated/content/cast-crew/': typeof AuthenticatedContentCastCrewIndexRoute
  '/_authenticated/content/channels/': typeof AuthenticatedContentChannelsIndexRoute
  '/_authenticated/content/episodes/': typeof AuthenticatedContentEpisodesIndexRoute
  '/_authenticated/content/genres/': typeof AuthenticatedContentGenresIndexRoute
  '/_authenticated/content/movies/': typeof AuthenticatedContentMoviesIndexRoute
  '/_authenticated/content/seasons/': typeof AuthenticatedContentSeasonsIndexRoute
  '/_authenticated/content/tv-shows/': typeof AuthenticatedContentTvShowsIndexRoute
  '/_authenticated/content/videos/': typeof AuthenticatedContentVideosIndexRoute
  '/_authenticated/engagement/comments/': typeof AuthenticatedEngagementCommentsIndexRoute
  '/_authenticated/engagement/reports/': typeof AuthenticatedEngagementReportsIndexRoute
  '/_authenticated/engagement/reviews/': typeof AuthenticatedEngagementReviewsIndexRoute
  '/_authenticated/monetization/coupons/': typeof AuthenticatedMonetizationCouponsIndexRoute
  '/_authenticated/monetization/payment-methods/': typeof AuthenticatedMonetizationPaymentMethodsIndexRoute
  '/_authenticated/monetization/plans/': typeof AuthenticatedMonetizationPlansIndexRoute
  '/_authenticated/monetization/taxes/': typeof AuthenticatedMonetizationTaxesIndexRoute
  '/_authenticated/monetization/transactions/': typeof AuthenticatedMonetizationTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password/$token'
    | '/dashboard'
    | '/users'
    | '/content/episodes/$id'
    | '/content/movies/$id'
    | '/content/seasons/$id'
    | '/content/tv-shows/$id'
    | '/cms/banners'
    | '/cms/pages'
    | '/cms/settings'
    | '/content/cast-crew'
    | '/content/channels'
    | '/content/episodes'
    | '/content/genres'
    | '/content/movies'
    | '/content/seasons'
    | '/content/tv-shows'
    | '/content/videos'
    | '/engagement/comments'
    | '/engagement/reports'
    | '/engagement/reviews'
    | '/monetization/coupons'
    | '/monetization/payment-methods'
    | '/monetization/plans'
    | '/monetization/taxes'
    | '/monetization/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password/$token'
    | '/dashboard'
    | '/users'
    | '/content/episodes/$id'
    | '/content/movies/$id'
    | '/content/seasons/$id'
    | '/content/tv-shows/$id'
    | '/cms/banners'
    | '/cms/pages'
    | '/cms/settings'
    | '/content/cast-crew'
    | '/content/channels'
    | '/content/episodes'
    | '/content/genres'
    | '/content/movies'
    | '/content/seasons'
    | '/content/tv-shows'
    | '/content/videos'
    | '/engagement/comments'
    | '/engagement/reports'
    | '/engagement/reviews'
    | '/monetization/coupons'
    | '/monetization/payment-methods'
    | '/monetization/plans'
    | '/monetization/taxes'
    | '/monetization/transactions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password/$token'
    | '/_authenticated/dashboard/'
    | '/_authenticated/users/'
    | '/_authenticated/content/episodes/$id'
    | '/_authenticated/content/movies/$id'
    | '/_authenticated/content/seasons/$id'
    | '/_authenticated/content/tv-shows/$id'
    | '/_authenticated/cms/banners/'
    | '/_authenticated/cms/pages/'
    | '/_authenticated/cms/settings/'
    | '/_authenticated/content/cast-crew/'
    | '/_authenticated/content/channels/'
    | '/_authenticated/content/episodes/'
    | '/_authenticated/content/genres/'
    | '/_authenticated/content/movies/'
    | '/_authenticated/content/seasons/'
    | '/_authenticated/content/tv-shows/'
    | '/_authenticated/content/videos/'
    | '/_authenticated/engagement/comments/'
    | '/_authenticated/engagement/reports/'
    | '/_authenticated/engagement/reviews/'
    | '/_authenticated/monetization/coupons/'
    | '/_authenticated/monetization/payment-methods/'
    | '/_authenticated/monetization/plans/'
    | '/_authenticated/monetization/taxes/'
    | '/_authenticated/monetization/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/$token': {
      id: '/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof ResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/monetization/transactions/': {
      id: '/_authenticated/monetization/transactions/'
      path: '/monetization/transactions'
      fullPath: '/monetization/transactions'
      preLoaderRoute: typeof AuthenticatedMonetizationTransactionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/monetization/taxes/': {
      id: '/_authenticated/monetization/taxes/'
      path: '/monetization/taxes'
      fullPath: '/monetization/taxes'
      preLoaderRoute: typeof AuthenticatedMonetizationTaxesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/monetization/plans/': {
      id: '/_authenticated/monetization/plans/'
      path: '/monetization/plans'
      fullPath: '/monetization/plans'
      preLoaderRoute: typeof AuthenticatedMonetizationPlansIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/monetization/payment-methods/': {
      id: '/_authenticated/monetization/payment-methods/'
      path: '/monetization/payment-methods'
      fullPath: '/monetization/payment-methods'
      preLoaderRoute: typeof AuthenticatedMonetizationPaymentMethodsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/monetization/coupons/': {
      id: '/_authenticated/monetization/coupons/'
      path: '/monetization/coupons'
      fullPath: '/monetization/coupons'
      preLoaderRoute: typeof AuthenticatedMonetizationCouponsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/engagement/reviews/': {
      id: '/_authenticated/engagement/reviews/'
      path: '/engagement/reviews'
      fullPath: '/engagement/reviews'
      preLoaderRoute: typeof AuthenticatedEngagementReviewsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/engagement/reports/': {
      id: '/_authenticated/engagement/reports/'
      path: '/engagement/reports'
      fullPath: '/engagement/reports'
      preLoaderRoute: typeof AuthenticatedEngagementReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/engagement/comments/': {
      id: '/_authenticated/engagement/comments/'
      path: '/engagement/comments'
      fullPath: '/engagement/comments'
      preLoaderRoute: typeof AuthenticatedEngagementCommentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/content/videos/': {
      id: '/_authenticated/content/videos/'
      path: '/content/videos'
      fullPath: '/content/videos'
      preLoaderRoute: typeof AuthenticatedContentVideosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/content/tv-shows/': {
      id: '/_authenticated/content/tv-shows/'
      path: '/content/tv-shows'
      fullPath: '/content/tv-shows'
      preLoaderRoute: typeof AuthenticatedContentTvShowsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/content/seasons/': {
      id: '/_authenticated/content/seasons/'
      path: '/content/seasons'
      fullPath: '/content/seasons'
      preLoaderRoute: typeof AuthenticatedContentSeasonsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/content/movies/': {
      id: '/_authenticated/content/movies/'
      path: '/content/movies'
      fullPath: '/content/movies'
      preLoaderRoute: typeof AuthenticatedContentMoviesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/content/genres/': {
      id: '/_authenticated/content/genres/'
      path: '/content/genres'
      fullPath: '/content/genres'
      preLoaderRoute: typeof AuthenticatedContentGenresIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/content/episodes/': {
      id: '/_authenticated/content/episodes/'
      path: '/content/episodes'
      fullPath: '/content/episodes'
      preLoaderRoute: typeof AuthenticatedContentEpisodesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/content/channels/': {
      id: '/_authenticated/content/channels/'
      path: '/content/channels'
      fullPath: '/content/channels'
      preLoaderRoute: typeof AuthenticatedContentChannelsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/content/cast-crew/': {
      id: '/_authenticated/content/cast-crew/'
      path: '/content/cast-crew'
      fullPath: '/content/cast-crew'
      preLoaderRoute: typeof AuthenticatedContentCastCrewIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cms/settings/': {
      id: '/_authenticated/cms/settings/'
      path: '/cms/settings'
      fullPath: '/cms/settings'
      preLoaderRoute: typeof AuthenticatedCmsSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cms/pages/': {
      id: '/_authenticated/cms/pages/'
      path: '/cms/pages'
      fullPath: '/cms/pages'
      preLoaderRoute: typeof AuthenticatedCmsPagesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cms/banners/': {
      id: '/_authenticated/cms/banners/'
      path: '/cms/banners'
      fullPath: '/cms/banners'
      preLoaderRoute: typeof AuthenticatedCmsBannersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/content/tv-shows/$id': {
      id: '/_authenticated/content/tv-shows/$id'
      path: '/content/tv-shows/$id'
      fullPath: '/content/tv-shows/$id'
      preLoaderRoute: typeof AuthenticatedContentTvShowsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/content/seasons/$id': {
      id: '/_authenticated/content/seasons/$id'
      path: '/content/seasons/$id'
      fullPath: '/content/seasons/$id'
      preLoaderRoute: typeof AuthenticatedContentSeasonsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/content/movies/$id': {
      id: '/_authenticated/content/movies/$id'
      path: '/content/movies/$id'
      fullPath: '/content/movies/$id'
      preLoaderRoute: typeof AuthenticatedContentMoviesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/content/episodes/$id': {
      id: '/_authenticated/content/episodes/$id'
      path: '/content/episodes/$id'
      fullPath: '/content/episodes/$id'
      preLoaderRoute: typeof AuthenticatedContentEpisodesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedContentEpisodesIdRoute: typeof AuthenticatedContentEpisodesIdRoute
  AuthenticatedContentMoviesIdRoute: typeof AuthenticatedContentMoviesIdRoute
  AuthenticatedContentSeasonsIdRoute: typeof AuthenticatedContentSeasonsIdRoute
  AuthenticatedContentTvShowsIdRoute: typeof AuthenticatedContentTvShowsIdRoute
  AuthenticatedCmsBannersIndexRoute: typeof AuthenticatedCmsBannersIndexRoute
  AuthenticatedCmsPagesIndexRoute: typeof AuthenticatedCmsPagesIndexRoute
  AuthenticatedCmsSettingsIndexRoute: typeof AuthenticatedCmsSettingsIndexRoute
  AuthenticatedContentCastCrewIndexRoute: typeof AuthenticatedContentCastCrewIndexRoute
  AuthenticatedContentChannelsIndexRoute: typeof AuthenticatedContentChannelsIndexRoute
  AuthenticatedContentEpisodesIndexRoute: typeof AuthenticatedContentEpisodesIndexRoute
  AuthenticatedContentGenresIndexRoute: typeof AuthenticatedContentGenresIndexRoute
  AuthenticatedContentMoviesIndexRoute: typeof AuthenticatedContentMoviesIndexRoute
  AuthenticatedContentSeasonsIndexRoute: typeof AuthenticatedContentSeasonsIndexRoute
  AuthenticatedContentTvShowsIndexRoute: typeof AuthenticatedContentTvShowsIndexRoute
  AuthenticatedContentVideosIndexRoute: typeof AuthenticatedContentVideosIndexRoute
  AuthenticatedEngagementCommentsIndexRoute: typeof AuthenticatedEngagementCommentsIndexRoute
  AuthenticatedEngagementReportsIndexRoute: typeof AuthenticatedEngagementReportsIndexRoute
  AuthenticatedEngagementReviewsIndexRoute: typeof AuthenticatedEngagementReviewsIndexRoute
  AuthenticatedMonetizationCouponsIndexRoute: typeof AuthenticatedMonetizationCouponsIndexRoute
  AuthenticatedMonetizationPaymentMethodsIndexRoute: typeof AuthenticatedMonetizationPaymentMethodsIndexRoute
  AuthenticatedMonetizationPlansIndexRoute: typeof AuthenticatedMonetizationPlansIndexRoute
  AuthenticatedMonetizationTaxesIndexRoute: typeof AuthenticatedMonetizationTaxesIndexRoute
  AuthenticatedMonetizationTransactionsIndexRoute: typeof AuthenticatedMonetizationTransactionsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedContentEpisodesIdRoute: AuthenticatedContentEpisodesIdRoute,
  AuthenticatedContentMoviesIdRoute: AuthenticatedContentMoviesIdRoute,
  AuthenticatedContentSeasonsIdRoute: AuthenticatedContentSeasonsIdRoute,
  AuthenticatedContentTvShowsIdRoute: AuthenticatedContentTvShowsIdRoute,
  AuthenticatedCmsBannersIndexRoute: AuthenticatedCmsBannersIndexRoute,
  AuthenticatedCmsPagesIndexRoute: AuthenticatedCmsPagesIndexRoute,
  AuthenticatedCmsSettingsIndexRoute: AuthenticatedCmsSettingsIndexRoute,
  AuthenticatedContentCastCrewIndexRoute:
    AuthenticatedContentCastCrewIndexRoute,
  AuthenticatedContentChannelsIndexRoute:
    AuthenticatedContentChannelsIndexRoute,
  AuthenticatedContentEpisodesIndexRoute:
    AuthenticatedContentEpisodesIndexRoute,
  AuthenticatedContentGenresIndexRoute: AuthenticatedContentGenresIndexRoute,
  AuthenticatedContentMoviesIndexRoute: AuthenticatedContentMoviesIndexRoute,
  AuthenticatedContentSeasonsIndexRoute: AuthenticatedContentSeasonsIndexRoute,
  AuthenticatedContentTvShowsIndexRoute: AuthenticatedContentTvShowsIndexRoute,
  AuthenticatedContentVideosIndexRoute: AuthenticatedContentVideosIndexRoute,
  AuthenticatedEngagementCommentsIndexRoute:
    AuthenticatedEngagementCommentsIndexRoute,
  AuthenticatedEngagementReportsIndexRoute:
    AuthenticatedEngagementReportsIndexRoute,
  AuthenticatedEngagementReviewsIndexRoute:
    AuthenticatedEngagementReviewsIndexRoute,
  AuthenticatedMonetizationCouponsIndexRoute:
    AuthenticatedMonetizationCouponsIndexRoute,
  AuthenticatedMonetizationPaymentMethodsIndexRoute:
    AuthenticatedMonetizationPaymentMethodsIndexRoute,
  AuthenticatedMonetizationPlansIndexRoute:
    AuthenticatedMonetizationPlansIndexRoute,
  AuthenticatedMonetizationTaxesIndexRoute:
    AuthenticatedMonetizationTaxesIndexRoute,
  AuthenticatedMonetizationTransactionsIndexRoute:
    AuthenticatedMonetizationTransactionsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
