/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as ProfilesRouteImport } from './routes/profiles'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PricingIndexRouteImport } from './routes/pricing/index'
import { Route as LiveIndexRouteImport } from './routes/live/index'
import { Route as CatalogIndexRouteImport } from './routes/catalog/index'
import { Route as WatchVideoIdRouteImport } from './routes/watch/$videoId'
import { Route as TvShowsIdRouteImport } from './routes/tv-shows/$id'
import { Route as SeasonsSeasonIdRouteImport } from './routes/seasons/$seasonId'
import { Route as ResetPasswordTokenRouteImport } from './routes/reset-password.$token'
import { Route as PaymentSuccessRouteImport } from './routes/payment/success'
import { Route as PaymentCancelRouteImport } from './routes/payment/cancel'
import { Route as PagesSlugRouteImport } from './routes/pages/$slug'
import { Route as MoviesIdRouteImport } from './routes/movies/$id'
import { Route as InterviewIdRouteImport } from './routes/interview/$id'
import { Route as EpisodesIdRouteImport } from './routes/episodes/$id'
import { Route as CategoryCategoryIdRouteImport } from './routes/category/$categoryId'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as CategorySimpleCategoryIdRouteImport } from './routes/category/simple/$categoryId'
import { Route as TvShowsIdSeasonsSeasonIdRouteImport } from './routes/tv-shows/$id/seasons/$seasonId'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesRoute = ProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingIndexRoute = PricingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PricingRoute,
} as any)
const LiveIndexRoute = LiveIndexRouteImport.update({
  id: '/live/',
  path: '/live/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchVideoIdRoute = WatchVideoIdRouteImport.update({
  id: '/watch/$videoId',
  path: '/watch/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const TvShowsIdRoute = TvShowsIdRouteImport.update({
  id: '/tv-shows/$id',
  path: '/tv-shows/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonsSeasonIdRoute = SeasonsSeasonIdRouteImport.update({
  id: '/seasons/$seasonId',
  path: '/seasons/$seasonId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCancelRoute = PaymentCancelRouteImport.update({
  id: '/payment/cancel',
  path: '/payment/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIdRoute = MoviesIdRouteImport.update({
  id: '/movies/$id',
  path: '/movies/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewIdRoute = InterviewIdRouteImport.update({
  id: '/interview/$id',
  path: '/interview/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodesIdRoute = EpisodesIdRouteImport.update({
  id: '/episodes/$id',
  path: '/episodes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryIdRoute = CategoryCategoryIdRouteImport.update({
  id: '/category/$categoryId',
  path: '/category/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySimpleCategoryIdRoute =
  CategorySimpleCategoryIdRouteImport.update({
    id: '/category/simple/$categoryId',
    path: '/category/simple/$categoryId',
    getParentRoute: () => rootRouteImport,
  } as any)
const TvShowsIdSeasonsSeasonIdRoute =
  TvShowsIdSeasonsSeasonIdRouteImport.update({
    id: '/seasons/$seasonId',
    path: '/seasons/$seasonId',
    getParentRoute: () => TvShowsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/devices': typeof DevicesRoute
  '/pricing': typeof PricingRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/profiles': typeof ProfilesRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/transactions': typeof TransactionsRoute
  '/watchlist': typeof WatchlistRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/episodes/$id': typeof EpisodesIdRoute
  '/interview/$id': typeof InterviewIdRoute
  '/movies/$id': typeof MoviesIdRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/seasons/$seasonId': typeof SeasonsSeasonIdRoute
  '/tv-shows/$id': typeof TvShowsIdRouteWithChildren
  '/watch/$videoId': typeof WatchVideoIdRoute
  '/catalog': typeof CatalogIndexRoute
  '/live': typeof LiveIndexRoute
  '/pricing/': typeof PricingIndexRoute
  '/category/simple/$categoryId': typeof CategorySimpleCategoryIdRoute
  '/tv-shows/$id/seasons/$seasonId': typeof TvShowsIdSeasonsSeasonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/devices': typeof DevicesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/profiles': typeof ProfilesRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/transactions': typeof TransactionsRoute
  '/watchlist': typeof WatchlistRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/episodes/$id': typeof EpisodesIdRoute
  '/interview/$id': typeof InterviewIdRoute
  '/movies/$id': typeof MoviesIdRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/seasons/$seasonId': typeof SeasonsSeasonIdRoute
  '/tv-shows/$id': typeof TvShowsIdRouteWithChildren
  '/watch/$videoId': typeof WatchVideoIdRoute
  '/catalog': typeof CatalogIndexRoute
  '/live': typeof LiveIndexRoute
  '/pricing': typeof PricingIndexRoute
  '/category/simple/$categoryId': typeof CategorySimpleCategoryIdRoute
  '/tv-shows/$id/seasons/$seasonId': typeof TvShowsIdSeasonsSeasonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/devices': typeof DevicesRoute
  '/pricing': typeof PricingRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/profiles': typeof ProfilesRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/transactions': typeof TransactionsRoute
  '/watchlist': typeof WatchlistRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/episodes/$id': typeof EpisodesIdRoute
  '/interview/$id': typeof InterviewIdRoute
  '/movies/$id': typeof MoviesIdRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/seasons/$seasonId': typeof SeasonsSeasonIdRoute
  '/tv-shows/$id': typeof TvShowsIdRouteWithChildren
  '/watch/$videoId': typeof WatchVideoIdRoute
  '/catalog/': typeof CatalogIndexRoute
  '/live/': typeof LiveIndexRoute
  '/pricing/': typeof PricingIndexRoute
  '/category/simple/$categoryId': typeof CategorySimpleCategoryIdRoute
  '/tv-shows/$id/seasons/$seasonId': typeof TvShowsIdSeasonsSeasonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/devices'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/profiles'
    | '/subscriptions'
    | '/transactions'
    | '/watchlist'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/category/$categoryId'
    | '/episodes/$id'
    | '/interview/$id'
    | '/movies/$id'
    | '/pages/$slug'
    | '/payment/cancel'
    | '/payment/success'
    | '/reset-password/$token'
    | '/seasons/$seasonId'
    | '/tv-shows/$id'
    | '/watch/$videoId'
    | '/catalog'
    | '/live'
    | '/pricing/'
    | '/category/simple/$categoryId'
    | '/tv-shows/$id/seasons/$seasonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/devices'
    | '/privacy'
    | '/profile'
    | '/profiles'
    | '/subscriptions'
    | '/transactions'
    | '/watchlist'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/category/$categoryId'
    | '/episodes/$id'
    | '/interview/$id'
    | '/movies/$id'
    | '/pages/$slug'
    | '/payment/cancel'
    | '/payment/success'
    | '/reset-password/$token'
    | '/seasons/$seasonId'
    | '/tv-shows/$id'
    | '/watch/$videoId'
    | '/catalog'
    | '/live'
    | '/pricing'
    | '/category/simple/$categoryId'
    | '/tv-shows/$id/seasons/$seasonId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/devices'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/profiles'
    | '/subscriptions'
    | '/transactions'
    | '/watchlist'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/category/$categoryId'
    | '/episodes/$id'
    | '/interview/$id'
    | '/movies/$id'
    | '/pages/$slug'
    | '/payment/cancel'
    | '/payment/success'
    | '/reset-password/$token'
    | '/seasons/$seasonId'
    | '/tv-shows/$id'
    | '/watch/$videoId'
    | '/catalog/'
    | '/live/'
    | '/pricing/'
    | '/category/simple/$categoryId'
    | '/tv-shows/$id/seasons/$seasonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DevicesRoute: typeof DevicesRoute
  PricingRoute: typeof PricingRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ProfilesRoute: typeof ProfilesRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  TransactionsRoute: typeof TransactionsRoute
  WatchlistRoute: typeof WatchlistRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  CategoryCategoryIdRoute: typeof CategoryCategoryIdRoute
  EpisodesIdRoute: typeof EpisodesIdRoute
  InterviewIdRoute: typeof InterviewIdRoute
  MoviesIdRoute: typeof MoviesIdRoute
  PagesSlugRoute: typeof PagesSlugRoute
  PaymentCancelRoute: typeof PaymentCancelRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
  SeasonsSeasonIdRoute: typeof SeasonsSeasonIdRoute
  TvShowsIdRoute: typeof TvShowsIdRouteWithChildren
  WatchVideoIdRoute: typeof WatchVideoIdRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
  LiveIndexRoute: typeof LiveIndexRoute
  CategorySimpleCategoryIdRoute: typeof CategorySimpleCategoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles': {
      id: '/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof ProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing/': {
      id: '/pricing/'
      path: '/'
      fullPath: '/pricing/'
      preLoaderRoute: typeof PricingIndexRouteImport
      parentRoute: typeof PricingRoute
    }
    '/live/': {
      id: '/live/'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$videoId': {
      id: '/watch/$videoId'
      path: '/watch/$videoId'
      fullPath: '/watch/$videoId'
      preLoaderRoute: typeof WatchVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv-shows/$id': {
      id: '/tv-shows/$id'
      path: '/tv-shows/$id'
      fullPath: '/tv-shows/$id'
      preLoaderRoute: typeof TvShowsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasons/$seasonId': {
      id: '/seasons/$seasonId'
      path: '/seasons/$seasonId'
      fullPath: '/seasons/$seasonId'
      preLoaderRoute: typeof SeasonsSeasonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/$token': {
      id: '/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof ResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/cancel': {
      id: '/payment/cancel'
      path: '/payment/cancel'
      fullPath: '/payment/cancel'
      preLoaderRoute: typeof PaymentCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$id': {
      id: '/movies/$id'
      path: '/movies/$id'
      fullPath: '/movies/$id'
      preLoaderRoute: typeof MoviesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/$id': {
      id: '/interview/$id'
      path: '/interview/$id'
      fullPath: '/interview/$id'
      preLoaderRoute: typeof InterviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodes/$id': {
      id: '/episodes/$id'
      path: '/episodes/$id'
      fullPath: '/episodes/$id'
      preLoaderRoute: typeof EpisodesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$categoryId': {
      id: '/category/$categoryId'
      path: '/category/$categoryId'
      fullPath: '/category/$categoryId'
      preLoaderRoute: typeof CategoryCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/simple/$categoryId': {
      id: '/category/simple/$categoryId'
      path: '/category/simple/$categoryId'
      fullPath: '/category/simple/$categoryId'
      preLoaderRoute: typeof CategorySimpleCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv-shows/$id/seasons/$seasonId': {
      id: '/tv-shows/$id/seasons/$seasonId'
      path: '/seasons/$seasonId'
      fullPath: '/tv-shows/$id/seasons/$seasonId'
      preLoaderRoute: typeof TvShowsIdSeasonsSeasonIdRouteImport
      parentRoute: typeof TvShowsIdRoute
    }
  }
}

interface PricingRouteChildren {
  PricingIndexRoute: typeof PricingIndexRoute
}

const PricingRouteChildren: PricingRouteChildren = {
  PricingIndexRoute: PricingIndexRoute,
}

const PricingRouteWithChildren =
  PricingRoute._addFileChildren(PricingRouteChildren)

interface TvShowsIdRouteChildren {
  TvShowsIdSeasonsSeasonIdRoute: typeof TvShowsIdSeasonsSeasonIdRoute
}

const TvShowsIdRouteChildren: TvShowsIdRouteChildren = {
  TvShowsIdSeasonsSeasonIdRoute: TvShowsIdSeasonsSeasonIdRoute,
}

const TvShowsIdRouteWithChildren = TvShowsIdRoute._addFileChildren(
  TvShowsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DevicesRoute: DevicesRoute,
  PricingRoute: PricingRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ProfilesRoute: ProfilesRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  TransactionsRoute: TransactionsRoute,
  WatchlistRoute: WatchlistRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  CategoryCategoryIdRoute: CategoryCategoryIdRoute,
  EpisodesIdRoute: EpisodesIdRoute,
  InterviewIdRoute: InterviewIdRoute,
  MoviesIdRoute: MoviesIdRoute,
  PagesSlugRoute: PagesSlugRoute,
  PaymentCancelRoute: PaymentCancelRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
  SeasonsSeasonIdRoute: SeasonsSeasonIdRoute,
  TvShowsIdRoute: TvShowsIdRouteWithChildren,
  WatchVideoIdRoute: WatchVideoIdRoute,
  CatalogIndexRoute: CatalogIndexRoute,
  LiveIndexRoute: LiveIndexRoute,
  CategorySimpleCategoryIdRoute: CategorySimpleCategoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
